# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNF_3KZ1CiCHcZgnlNJiqEMO9q3c1PE7
"""

from api.weather_api import WeatherApp

def test_api():
    app = WeatherApp("Tehran")
    data = app.get_weather_data()
    assert "main" in data, "داده‌ها درست دریافت نشده"
    assert "temp" in data["main"], "دمای شهر موجود نیست"
    print("✅ تست API موفق بود")

if __name__ == "__main__":
    test_api()