# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNF_3KZ1CiCHcZgnlNJiqEMO9q3c1PE7
"""

import matplotlib.pyplot as plt

def plot_temperature(city, temperature):
    plt.figure()
    plt.bar([city], [temperature])
    plt.title("نمودار دمای شهر")
    plt.xlabel("شهر")
    plt.ylabel("دما (°C)")
    plt.show()