# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNF_3KZ1CiCHcZgnlNJiqEMO9q3c1PE7
"""

import requests
import matplotlib.pyplot as plt

# کلاس اصلی
class WeatherApp:
    def __init__(self, city):
        self.city = city
        self.api_key = "cea9d848ea14a07e93c210e93b2eb1c8"
        self.url = (
            f"https://api.openweathermap.org/data/2.5/weather"
            f"?q={city}&appid={self.api_key}&units=metric&lang=fa"
        )

    def get_weather_data(self):
        response = requests.get(self.url)
        return response.json()

# تابع رسم نمودار
def plot_temperature(city, temperature):
    plt.figure()
    plt.bar([city], [temperature])
    plt.title("نمودار دمای شهر")
    plt.xlabel("شهر")
    plt.ylabel("دما (°C)")
    plt.show()

# اجرای برنامه
if __name__ == "__main__":
    city_name = input("نام شهر را به انگلیسی وارد کنید (مثلاً Tehran): ")
    app = WeatherApp(city_name)
    data = app.get_weather_data()

    if str(data.get("cod")) != "200":
        print("❌ خطا در دریافت اطلاعات آب‌وهوا")
        print("پیام API:", data.get("message"))
    else:
        temperature = data["main"]["temp"]
        humidity = data["main"]["humidity"]
        description = data["weather"][0]["description"]

        print("📍 شهر:", city_name)
        print("🌡 دما:", temperature, "درجه سانتی‌گراد")
        print("💧 رطوبت:", humidity, "درصد")
        print("☁ وضعیت هوا:", description)

        plot_temperature(city_name, temperature)