# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNF_3KZ1CiCHcZgnlNJiqEMO9q3c1PE7
"""

import requests

class WeatherApp:
    def __init__(self, city):
        self.city = city
        self.api_key = "cea9d848ea14a07e93c210e93b2eb1c8"
        self.url = (
            f"https://api.openweathermap.org/data/2.5/weather"
            f"?q={city}&appid={self.api_key}&units=metric&lang=fa"
        )

    def get_weather_data(self):
        response = requests.get(self.url)
        return response.json()